eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    url: jdbc:mysql://client-service.cfuskkuqotmo.us-east-1.rds.amazonaws.com:3306/client-service
    username: admin
    password: 123ayman
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

